package com.cstlabs.rmd.UIControl.Photos;

import java.io.ByteArrayOutputStream;

import android.graphics.Bitmap;
import android.graphics.Bitmap.CompressFormat;
import android.graphics.BitmapFactory;
/*
 * This class handles utility operations for photo oprations in system 
 * 
 * @author Akila Darshana Panditha
 * @version 1.0
 */
public class PhotoUtilities {

	
	/*
	 * converts bitmap to byte stream
	 * @param bitmap to be converted 
	 * @return generated byte stream from bitmap 
	 */
	public static byte[] getBytes(Bitmap bitmap) {
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		bitmap.compress(CompressFormat.PNG, 0, stream);
		return stream.toByteArray();
	}

	/*
	 * converts byte stram to bitmap 
	 * @param byte stream to be converted 
	 * @return generated bitmap 
	 */
	public static Bitmap getImage(byte[] image) {
		return BitmapFactory.decodeByteArray(image, 0, image.length);
	}
}
